/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vuelosfis.vista;

/**
 *
 * @author Dell G15
 */
public class VentanaResumen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaResumen.class.getName());
    private vuelosfis.controlador.ControladorVuelo controlador;
    private vuelosfis.modelo.Reserva reservaActual;
    private double totalCalculado = 0.0;
    
    /**
     * Creates new form VentanaResumen
     */
    public VentanaResumen() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtDetalle.setEditable(false); // Para que no puedan borrar el texto
    }

        
    public void mostrarResumen(String infoIda, double precioIda, String infoVuelta, double precioVuelta) {
        
        StringBuilder resumen = new StringBuilder();
        double total = 0.0;

        // 1. Agregar Vuelo de Ida
        resumen.append("VUELO DE IDA\n");
        resumen.append(infoIda).append("\n");
        resumen.append("Precio: $ ").append(String.format("%.2f", precioIda)).append("\n\n");
        total += precioIda;

        // 2. Agregar Vuelo de Vuelta (Solo si existe)
        if (precioVuelta > 0) {
            resumen.append("VUELO DE VUELTA\n");
            resumen.append(infoVuelta).append("\n");
            resumen.append("Precio: $ ").append(String.format("%.2f", precioVuelta)).append("\n\n");
            total += precioVuelta;
        }

        // Guardar el total en la variable de clase 
        this.totalCalculado = total;
        
        // 3. Mostrar en pantalla
        txtDetalle.setText(resumen.toString());
        lblTotal.setText("Subtotal: $ " + String.format("%.2f", total));
    }
    
    public void setControlador(vuelosfis.controlador.ControladorVuelo controlador) {
        this.controlador = controlador;
    }
    
    public void setReserva(vuelosfis.modelo.Reserva reserva) {
        this.reservaActual = reserva;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();
        lblTotal = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel1.setText("Resumen de tu Viaje");

        txtDetalle.setColumns(20);
        txtDetalle.setRows(5);
        jScrollPane1.setViewportView(txtDetalle);

        lblTotal.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        lblTotal.setText("Subtotal: $");

        btnComprar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(this::btnComprarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(btnComprar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
if (this.reservaActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "❌ Error: No hay reserva activa.");
            return;
        }
        // --- GENERAR LA FACTURA FÍSICA ---
        // Llamamos al nuevo método que creamos en GestorArchivos
        vuelosfis.persistencia.GestorArchivos.generarFactura(
            this.reservaActual, 
            txtDetalle.getText(), // Pasamos el texto exacto que ve el usuario
            this.totalCalculado
        );

        // Mensaje de Éxito
        String msg = "✅ ¡Compra Exitosa!\n\n" +
                     "Se ha generado la factura: Factura_" + reservaActual.getCodigoReserva() + ".txt\n" +
                     "en la carpeta del proyecto.";
                     
        javax.swing.JOptionPane.showMessageDialog(this, msg);
        
        // Cerrar el programa
        System.exit(0);
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaResumen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextArea txtDetalle;
    // End of variables declaration//GEN-END:variables
}
