package vuelosfis.vista;

import javax.swing.table.DefaultTableModel;

public class VentanaVuelosIda extends javax.swing.JFrame {

    // Variables privadas
    private String origen;
    private String destino;
    private String fechaIda;
    private String fechaVuelta; 
    private int pasajeros;
    private boolean esIdaYVuelta;
    private String cabina;
    private String infoIdaPrev;
    private double precioIdaPrev = 0.0;
    private String infoVueltaActual; // Solo se usa si estamos en el paso final

    public VentanaVuelosIda() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // 1. Obtenemos el "modelo de selección" de la tabla
        javax.swing.ListSelectionModel selector = tblVuelos.getSelectionModel();
    }

    /**
     * INYECCIÓN DE DATOS
     */
    public void recibirDatos(String origen, String destino, String fechaIda, String fechaVuelta, 
            int pasajeros, boolean esRedondo, String cabina) {
        this.origen = origen;
        this.destino = destino;
        this.fechaIda = fechaIda;
        this.fechaVuelta = fechaVuelta; // Guardamos la fecha de vuelta
        this.pasajeros = pasajeros;
        this.esIdaYVuelta = esRedondo;  // Guardamos si es viaje redondo
        this.cabina = cabina;
        
        // Ejecutamos nuestra lógica visual
        actualizarTitulo();
        cargarTablaEstiloLATAM();
    }

    /**
     * Método 1: Actualiza el texto de arriba
     */
    private void actualizarTitulo() {
        // Usamos el Label(lblTitulo)
        lblTitulo.setText("Vuelos encontrados: " + origen + " - " + destino);
        
        // También cambiamos el título de la ventana flotante
        this.setTitle("Resultados para " + pasajeros + " pasajero(s) - Fecha: " + fechaIda);
    }

    /**
     * Método 2: Crea la tabla bonita y la llena de datos falsos
     */
    private void cargarTablaEstiloLATAM() {
        // A. Definimos las columnas
        String[] columnas = {
            "Salida", "Llegada", "Duración", "Tipo", "Precio"
        };

        // B. Modelo de datos (Bloqueamos edición para que no escriban en la tabla)
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        // D. Asignar el modelo a TU tabla
        tblVuelos.setModel(modelo);
        
        // Esto bloquea que se pueda cambiar el tamaño de las columnas
        tblVuelos.getTableHeader().setResizingAllowed(false);
        
        // Opcional: Esto bloquea que las muevan de lugar
        tblVuelos.getTableHeader().setReorderingAllowed(false);
    }
    
    public void setDatosPrevios(String infoIda, double precioIda, String infoVuelta) {
        this.infoIdaPrev = infoIda;
        this.precioIdaPrev = precioIda;
        this.infoVueltaActual = infoVuelta;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelos = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        lblTitulo.setText("Vuelos encontrados:");

        tblVuelos.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        tblVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Salida", "Llegada", "Duración", "Tipo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVuelos);

        btnSeleccionar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnSeleccionar.setText("Continuar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.setToolTipText("");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionar)
                    .addComponent(btnAtras))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
    // 1. Crear una nueva instancia de la Ventana Principal
    VentanaPrincipal ventana1 = new VentanaPrincipal();
    
    // 2. Hacerla visible y centrarla
    ventana1.setVisible(true);
    ventana1.setLocationRelativeTo(null);
    
    // 3. Cerrar esta ventana actual de resultados
    this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
    // 1. Verificar selección
        int fila = tblVuelos.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un vuelo para continuar.");
            return;
        }

        String precio = tblVuelos.getValueAt(fila, 4).toString();

        this.setVisible(false);
        VentanaSeleccionTarifa vTarifas = new VentanaSeleccionTarifa();

        // AQUÍ ESTABA EL ERROR: AHORA PASAMOS 'this.cabina' AL FINAL
        vTarifas.inicializar(origen, destino, fechaIda, precio, pasajeros, esIdaYVuelta, true, fechaVuelta, this.cabina); // <--- CORREGIDO

        vTarifas.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaVuelosIda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblVuelos;
    // End of variables declaration//GEN-END:variables
}
