/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vuelosfis.vista;

/**
 *
 * @author Dell G15
 */
public class VentanaVuelosVuelta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaVuelosVuelta.class.getName());
    private java.util.ArrayList<vuelosfis.modelo.Vuelo> listaResultadosVuelta;
    private vuelosfis.controlador.ControladorVuelo controlador;
    
    // Variables de Datos
    private String origen;
    private String destino;
    private String fechaVuelta;
    private int pasajeros;
    private String infoIdaGuardada;
    private double precioIdaGuardado;
    private String cabinaIdaGuardada;
    /**
     * Creates new form VentanaVuelosVuelta
     */
    public VentanaVuelosVuelta() {
        initComponents();
    }
    
// --- MÉTODO PARA RECIBIR DATOS ---
    public void recibirDatos(vuelosfis.controlador.ControladorVuelo ctrl,String origen, String destino, String fechaVuelta, int pasajeros,
                             String infoIda, double precioIda, String cabina) {
        this.controlador = ctrl;
        this.origen = origen;
        this.destino = destino;
        this.fechaVuelta = fechaVuelta;
        this.pasajeros = pasajeros;
        this.infoIdaGuardada = infoIda;
        this.precioIdaGuardado = precioIda;
        this.cabinaIdaGuardada = cabina;

        // Actualizamos los textos
        lblTitulo.setText("Vuelos de regreso: " + origen + " - " + destino);
        this.setTitle("Regreso - " + fechaVuelta);
        
        try {
        // 1. Le decimos a Java: "Oye, la fecha viene como dia/mes/año"
        java.time.format.DateTimeFormatter formatoEntrada = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        // 2. La convertimos correctamente
        java.time.LocalDate fechaConvertida = java.time.LocalDate.parse(fechaVuelta, formatoEntrada);
        
        // 3. Ahora sí buscamos sin errores
        this.listaResultadosVuelta = this.controlador.getControladorReserva().buscarVuelos(origen, destino, fechaConvertida);
        
    } catch (Exception e) {
        // Plan B: Si falla (por si acaso viniera al revés), intentamos el formato estándar
        try {
            this.listaResultadosVuelta = this.controlador.getControladorReserva().buscarVuelos(origen, destino, java.time.LocalDate.parse(fechaVuelta));
        } catch (Exception e2) {
            System.out.println("Error grave con la fecha de vuelta: " + fechaVuelta);
        }
    }
        configurarTablaConDatos(this.listaResultadosVuelta);
    }
    
    private void configurarTablaConDatos(java.util.ArrayList<vuelosfis.modelo.Vuelo> lista) {
        String[] columnas = {"Salida", "Llegada", "Duración", "Tipo", "Precio"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            public boolean isCellEditable(int row, int column) { return false; }
        };
        
        for (vuelosfis.modelo.Vuelo v : lista) {
            Object[] fila = {
                v.getHora(),
                v.getHora().plusMinutes(v.getRuta().getDuracion()), // Calculamos llegada aprox
                v.getRuta().getDuracion() + " min",
                v.getAvion().getModelo(),
                v.getPrecioBase()
            };
            modelo.addRow(fila);
        }
        tblVuelos.setModel(modelo);
    }
    
    // --- CONFIGURACIÓN DE TABLA ---
    private void configurarTablaSinDatos() {
    String[] columnas = {
            "Salida", "Llegada", "Duración", "Tipo", "Precio"
        };

        // Modelo que impide editar las celdas
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblVuelos.setModel(modelo);

        // Bloqueos visuales
        tblVuelos.getTableHeader().setResizingAllowed(false);
        tblVuelos.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelos = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        lblTitulo.setText("Vuelos de regreso:");

        tblVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Salida", "Llegada", "Duración", "Tipo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblVuelos);

        btnFinalizar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnFinalizar.setText("Continuar");
        btnFinalizar.addActionListener(this::btnFinalizarActionPerformed);

        btnAtras.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(this::btnAtrasActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizar)
                    .addComponent(btnAtras))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        int fila = tblVuelos.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un vuelo.");
            return;
        }

        // 1. Recuperamos el Vuelo
        vuelosfis.modelo.Vuelo vueloRetorno = this.listaResultadosVuelta.get(fila);
        String infoVuelta = "Regreso: " + vueloRetorno.getCodigo() + " (" + vueloRetorno.getHora() + ")";

        this.setVisible(false);
        VentanaSeleccionTarifa vTarifas = new VentanaSeleccionTarifa();

        // 2. Pasamos los datos (CON LA CORRECCIÓN DE FECHA)
        vTarifas.inicializar(
                this.controlador,   // Cerebro
                vueloRetorno,       // Vuelo Objeto
                origen, 
                destino, 
                fechaVuelta, 
                
                String.valueOf(vueloRetorno.getPrecioBase()), 
                pasajeros, 
                true,  // esRedondo
                false, // esIda
                null, 
                cabinaIdaGuardada
        );
        
        vTarifas.setDatosPrevios(infoIdaGuardada, precioIdaGuardado, infoVuelta);
        vTarifas.setVisible(true);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
    // Volver al inicio
    VentanaPrincipal v1 = new VentanaPrincipal();
    v1.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaVuelosVuelta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblVuelos;
    // End of variables declaration//GEN-END:variables
}
